README.md
Add topicbox link to README. I put it near the top so people will see, lmk if you'd prefer another location.
Support-seekers and coders alike can now discuss their respective topics on topicbox! 💯
=> update readme with topicbox info

backend/src/appointment/routes/zoom.py, backend/test/factory/schedule_factory.py, backend/test/integration/test_zoom.py, frontend/src/components/ScheduleCreation.vue
Just some small extra fixes here to go with https://github.com/thunderbird/appointment/pull/399
=> Additional zoom account fixes

tofu/modules/data-store/database/main.tf
Production database will now have deletion protection enabled and final snapshot enforced
Protects against potential data loss if RDS DB is deleted
=> corrected db protection for production

tofu/README.md
IaC documentation updates
Clarifies the process and requirements for manually running IaC & application deployments
=> IaC documentation update

frontend/src/elements/CalendarEvent.vue
Fixes #412 
This fixes a very annoying bug with the calendar randomly resizing. 
Visual demonstration:
https://github.com/thunderbird/appointment/assets/97147377/da5342f9-7496-4a41-bb3a-7dc73d43302c
=> Fix `whitespace: nowrap` expanding width of calendar days on month view.

.github/workflows/deploy-staging.yml
Should fix the detect-changes==true && detect-iac==false (or vice versa) skipping deployment jobs
=> Never skip a job unless deploy-app is false

backend/src/appointment/controller/mailer.py, backend/src/appointment/routes/api.py, backend/src/appointment/routes/schedule.py, backend/src/appointment/tasks/emails.py, backend/src/appointment/templates/email/confirm.jinja2, backend/src/appointment/templates/email/pending.jinja2, backend/src/appointment/templates/email/rejected.jinja2, backend/src/appointment/templates/email/support.jinja2, backend/test/unit/test_mailer.py
=> Don't use db models for emails

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, tofu/README.md
changes to github actions workflow triggers for deploy-staging.  Frontend and backend deployments now run if iac deployment is skipped or successfully completer
Ensures deploys run as expected, even if now IaC changes are needed
=> Cleanup workflow triggers

backend/requirements.txt, backend/src/appointment/database/models.py
Fixes #431 
I haven't encountered any issues locally.
=> Bump up SqlAlchemy to 2.0.30

.github/workflows/deploy-staging.yml
Missing environment variable added to deploy-staging workflow
Resolves broken stage deployments
=> added TV_VAR_frontend_url to deploy-staging workflow

backend/src/appointment/routes/auth.py, backend/test/integration/test_auth.py
=> Override the invite requirement if we're on an allow-list

backend/src/appointment/dependencies/auth.py, backend/src/appointment/routes/auth.py, backend/test/integration/test_auth.py
We test that the response is not 200, so it will work as-is right now. But it's just a little odd.
=> Fix permission check

.github/workflows/deploy-staging.yml
Release now includes production frontend build and IaC
- provides correct frontend build for production release
- fixes IaC to what was in place during staging tests
=> Release Improvements

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Updates the production release pipeline to use the new release (including IaC)
More consistent releases with frontend, backend, and IaC frozen to what was deployed to staging.
=> Release deployment updates

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Cleaned up formatting and added a missing OIDC permission
The production workflow will actually be able to connect to AWS!
=> missing permission & formatting

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Resolves issues with missing folder in production release
Moves us closer to full release automation by ensuring that publishing a release correctly updates the backend
=> Release pipeline troubleshooting

backend/.env.example, backend/Dockerfile, backend/deploy.dockerfile, backend/scripts/dev-entry.sh, backend/src/appointment/commands/setup.py, backend/src/appointment/routes/commands.py, docker-compose.yml
Fixes #448 
This should help folks setting up appointment for the first time.
=> Add first time setup command

.github/workflows/deploy-production.yml
Fixing reference to job names
The workflow might actually run
=> Fix references to jobs

.github/workflows/deploy-production.yml
production backend service deployment job was missing environment variables
backend deployment job will run
=> added missing env variables

tofu/environments/prod/environment.hcl
Added provider version constraints to prod environment
=> add provider requirements to prod

.github/workflows/deploy-production.yml
Added initialization of backend-service dependencies
=> added dependency prep to backend-service deployment

README.md
This is already in the frontend readme. I guess I missed this 😄
=> Remove duplicate information

.github/workflows/deploy-staging.yml
corrected job names in triggers
=> fixed job triggers

backend/README.md
Turns out I needed this command on hand...
=> Add some info on creating database migrations

backend/src/appointment/routes/account.py, frontend/.eslintrc.cjs, frontend/src/components/CalendarQalendar.vue, frontend/src/composables/dayjs.ts, frontend/src/models.ts, frontend/src/stores/alert-store.ts, frontend/src/stores/appointment-store.ts, frontend/src/stores/booking-modal-store.ts, frontend/src/stores/booking-view-store.ts, frontend/src/stores/calendar-store.ts, frontend/src/stores/external-connections-store.ts, frontend/src/stores/schedule-store.ts, frontend/src/stores/user-store.ts
This change introduces types for all our db models and pinia store implementations. This is a first version which is meant to be iterated on in future PRs. Also having a `models.ts` is probably fine for now, but we might want to discuss where to store our types long term. I couldn't find anything in the send repo.
The user store is the last store that's missing. Since it's a bit bigger, I'll do that in a separate PR next week.
_Edit:_ No separate PR. Added the user store TS now too.
=> Stores TypeScript

tofu/modules/services/frontend-infra/main.tf
This fixes the weird validation error AWS randomly started giving us.
=> Update IaC with new cloudfront function

backend/src/appointment/l10n/en/main.ftl, backend/src/appointment/routes/auth.py, backend/test/integration/test_auth.py
Second edition, this is the one that will actually work...oops.
=> Move invite code check to start of login flow, and add tests

backend/src/appointment/controller/apis/fxa_client.py
Ah forgot to merge this last part in.
=> Remove the now un-needed check

backend/src/appointment/l10n/de/main.ftl, backend/test/integration/test_general.py
Just the l10n addition for #511
=> Update German translation

tofu/modules/services/frontend-infra/main.tf
Just adding some more context if we ever have to look at this function again from the AWS console. It's not immediately clear why we add a slash
=> add some background to the CloudFront function fix

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, .github/workflows/validate.yml, tofu/environments/prod/services/backend-infra/terragrunt.hcl, tofu/environments/prod/services/frontend-infra/terragrunt.hcl, tofu/environments/stage/services/backend-infra/terragrunt.hcl, tofu/environments/stage/services/frontend-infra/terragrunt.hcl
removes hardcoded cert so it can be updated via github variables
=> Remove hardcoded cert

backend/src/appointment/database/schemas.py, backend/src/appointment/routes/waiting_list.py, backend/test/integration/test_waiting_list.py, frontend/src/elements/admin/AdminNav.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/router.ts, frontend/src/views/admin/WaitingListPanelView.vue
To get visibility on the waiting list, I've added a read-only admin panel view. 
Bit of a rush, we'll add the "Accept x number of peeps" as a later feature.
=> Waiting List Admin Panel (Readonly)

.github/workflows/deploy-staging.yml
added recursive flag to frontend zip command
=> added recursive flag to frontend zip command

frontend/src/components/CalendarQalendar.vue, frontend/src/components/SettingsGeneral.vue, frontend/src/definitions.ts, frontend/src/models.ts, frontend/src/utils.ts
This change adds types for our utility function collection. It also introduces color schemes as ts enum. Let me know your opinions on this.
Further implements #413
=> Utils TypeScript

README.md
Updated the README to reflect the current state of project.
=> Updated README to reflect current state of project.

frontend/src/main.ts
=> Only add slash if the apiUrl doesn't already have one. 

frontend/src/components/bookingView/BookingViewError.vue, frontend/src/components/bookingView/BookingViewSuccess.vue
This change adds a condition for the Try appointment button to only show up when not logged in after booking.
Closes #557
=> Show "Try appointment" CTA only when not logged in

backend/src/appointment/controller/calendar.py, backend/src/appointment/controller/mailer.py, backend/src/appointment/l10n/en/email.ftl, backend/src/appointment/routes/schedule.py, backend/src/appointment/tasks/emails.py, backend/test/factory/appointment_factory.py, backend/test/unit/test_calendar_tools.py
Fixes #586 
Fixes #588 
Fixes #584 
* Include meeting link url in the location field
* Auto confirm/accept booked meetings
* Update the confirm email subject to include the name of the person who requested the booking
They were all together so might as well stack 'em! The German localization needs a subject update.
=> Various ics/google event improvements (Fixes #586, #588, and #584)

frontend/src/App.vue, frontend/src/components/BookingModal.vue, frontend/src/components/bookingView/BookingViewError.vue, frontend/src/components/bookingView/BookingViewSlotSelection.vue, frontend/src/components/bookingView/BookingViewSuccess.vue, frontend/src/definitions.ts, frontend/src/keys.ts, frontend/src/main.ts, frontend/src/models.ts, frontend/src/stores/booking-modal-store.ts, frontend/src/stores/booking-view-store.ts, frontend/src/views/BookingConfirmationView.vue, frontend/src/views/BookingView.vue
This change adds types for all booking view components and `App.vue`.
- The script section was moved to the top in the vue files
- Typed keys were provided while keeping old keys for compatibility until all files are typed
=> Booking view and App TypeScript

backend/src/appointment/controller/mailer.py, backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/en/email.ftl, backend/src/appointment/routes/schedule.py, backend/src/appointment/tasks/emails.py, backend/src/appointment/templates/email/new_booking.jinja2, backend/test/conftest.py, backend/test/factory/schedule_factory.py, backend/test/integration/test_schedule.py, backend/test/unit/test_mailer.py
Fixes #596 
Just a super simple ugly email saying "Hey you have a booking now!!!"
=> New booking email for users without booking confirmation enabled

README.md
Added instructions on how to deploy.
We don't have explicit documentation here, so we should document it within the codebase
=> update readme with deploy instructions

frontend/src/components/ScheduleCreation.vue, frontend/src/locales/en.json, frontend/src/tbpro/elements/TextInput.vue
This change migrates text inputs, selects, primary buttons and secondary buttons to use tbpro components.
One step further to the new design.
Implements #460
=> Migrate schedule creation inputs and buttons to tbpro components

backend/src/appointment/database/models.py, backend/src/appointment/database/repo/invite.py, backend/src/appointment/database/schemas.py, backend/src/appointment/defines.py, backend/src/appointment/migrations/versions/2024_09_12_2047-5edcde3f14c6_add_owner_id_to_invites_table.py, backend/src/appointment/migrations/versions/2024_09_12_2048-01d80f00243f_add_10_invites_to_all_.py, backend/src/appointment/routes/api.py, backend/src/appointment/routes/auth.py, backend/src/appointment/routes/invite.py, backend/src/appointment/utils.py, backend/test/conftest.py, backend/test/factory/invite_factory.py, backend/test/factory/subscriber_factory.py, backend/test/integration/test_invite.py, backend/test/unit/test_models.py, backend/test/unit/test_utils.py, frontend/src/components/DataTable.vue, frontend/src/components/SettingsAccount.vue, frontend/src/components/UserInviteTable.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/LoginView.vue
Fixes #606 
cc @malini for review and q: Do we want to give them 10, or a smaller amount? 
This adds an ugly yet functional invite table to Account settings. 
(^ the invites listed won't work on stage or prod, sorry :D)
=> Give subscribers 10 invites

backend/src/appointment/controller/apis/google_client.py, backend/src/appointment/controller/calendar.py
This will also hide the events from the dashboard, but I think that's okay.
=> Filter out transparent events (Fixes #661)

backend/Dockerfile, backend/pyproject.toml
Upgrade the Backend Python version to 3.12
Upgrading to Python 3.12 brings performance improvements and other bug fix.
fix: #637
=> feat: Upgrade Backend Python to 3.12

frontend/package-lock.json, frontend/package.json, frontend/src/App.vue
- Brings all dependencies to their latest minor version
- Fixes https://github.com/thunderbird/appointment/security/dependabot/24
Note: Only eslint needs to be updated in the future, that's currently not possible due to a dependency conflict with `eslint-config-airbnb-base`:
```plain
Package                           Current  Wanted  Latest  Location                                       Depended by
@typescript-eslint/eslint-plugin   7.18.0  7.18.0   8.7.0  node_modules/@typescript-eslint/eslint-plugin  frontend
@typescript-eslint/parser          7.18.0  7.18.0   8.7.0  node_modules/@typescript-eslint/parser         frontend
eslint                             8.57.1  8.57.1  9.11.1  node_modules/eslint                            frontend
```
=> Dependency updates

backend/test/integration/test_schedule.py
Fixes #732 
Time objects were naive (not timezone aware) and I think that was skewing the tests during Daylight savings. Either way the values are now actually correct, so we'll see if this breaks again in about 4 or so months 😅
=> Make all test time objects timezone aware

frontend/src/components/FTUE/SetupSchedule.vue, frontend/src/components/ScheduleCreation.vue, frontend/src/stores/schedule-store.ts
Fixes #736
Time is confusing...Details are in the ticket.
=> Convert schedule's time-range based on the date it was updated. 

backend/test/unit/test_auth_dependency.py
Small fix in a couple of asserts in the auth unit test.
=> Small fix for auth unit test

backend/src/appointment/main.py
Fixes #746
Should hopefully fix the error logging.
=> Set caldav logger to critical to ignore error logs 

backend/test/unit/test_calendar_tools.py, backend/test/unit/test_fxa_client.py, backend/test/unit/test_models.py
Just some minor unit test fixes/updates.
=> Some minor unit test fixes and updates.

frontend/src/components/CalendarManagement.vue, frontend/src/components/CalendarMiniMonth.vue, frontend/src/components/NavBar.vue, frontend/src/components/ScheduleCreation.vue, frontend/src/components/SettingsAccount.vue, frontend/src/components/SettingsGeneral.vue, frontend/src/components/TabBar.vue, frontend/src/components/bookingView/BookingViewSlotSelection.vue, frontend/src/elements/UserAvatar.vue, frontend/src/views/AppointmentsView.vue, frontend/src/views/HomeView.vue, frontend/src/views/SettingsView.vue
Adding some `data-testid` attributes to some UI DOM elements that may be used by future E2E tests.
=> Add data-testid attributes

backend/src/appointment/routes/api.py
Just a code cleanup. I removed the backend API endpoints `/terms` and `/privacy`
Closes #827
=> Remove unused terms and privacy endpoints

frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/components/FTUE/SetupProfile.vue, frontend/src/components/FTUE/SetupSchedule.vue, frontend/src/components/ScheduleCreation.vue, frontend/src/components/SettingsAccount.vue, frontend/src/keys.ts, frontend/src/locales/de.json, frontend/src/locales/en.json
I'd make a joke here but I'm sure it would get caught by the profanity filter. 
So this just removes it entirely.
=> Remove the frontend profanity filter (Fixes #840)

frontend/.env.example, frontend/src/App.vue, frontend/src/views/ProfileView.vue
This PR fixes the metrics shown on the profile page to actually show the correct numbers on page load.
Fixes #875
=> Fix initialization of profile metrics

frontend/src/views/LoginView.vue
Sorry for stealing it @devmount, but I ran into it and I just had to fix it haha.
Fixes #907
=> Add the missing keyup/submit.prevent to the login form element

backend/src/appointment/controller/calendar.py, backend/src/appointment/utils.py, backend/test/unit/test_calendar_tools.py
This PR makes the way we check for hostnames more precise.
Fixes #904
=> Fix url parsing issues

frontend/src/components/SettingsAccount.vue
Restores the tooltip functionality which somehow got lost.
Tooltip shows again on hover/focus.
Closes #902
=> Fix account settings tooltip

frontend/src/components/FTUE/ConnectCalendars.vue, frontend/src/components/FTUE/ConnectVideo.vue, frontend/src/components/FTUE/GoogleOauthProvider.vue, frontend/src/components/FTUE/SetupSchedule.vue
This may fix #908 
But basically these *Message variables are null by default, but we try to set them as if they're an Alert type. So lets set the entire object. This fixes FTUE calendar list on my end.
=> Set banner messages with the alert type, instead of trying to set a nullable value's title. 

frontend/src/views/admin/InviteCodePanelView.vue, frontend/src/views/admin/SubscriberPanelView.vue, frontend/src/views/admin/WaitingListPanelView.vue
Not critical because it's not something folks can access without permission. 
Note this function is not baseline, however it's in Firefox and Safari, and will be shipping soon in Chrome-based browsers
https://chromium-review.googlesource.com/c/chromium/src/+/6305455
=> Escape regex in admin panel search filter

backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/en/email.ftl
We aren't clear that the user has to sign in with the email address on file, so I've update the text to reflect this. 
Fewer confused invite recipients
=> update template with a bit more info on what to sign up with

backend/src/appointment/routes/invite.py, backend/test/integration/test_invite.py
=> Fix Admin/Invites not returning the proper total_pages count (Fixes #943)

frontend/src/components/FTUE/GoogleOauthProvider.vue, frontend/src/components/FTUE/SetupSchedule.vue, frontend/src/stores/appointment-store.ts, frontend/src/utils.ts
This change removes unused imports and fixes type issues.
Closes #935
=> Fix unused imports and types

.github/workflows/deploy-staging.yml
=> Fix GHA stage e2e test job trigger

backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/en/email.ftl
Fixes copy in the subject and body of the booking confirmation mail.
Fixes #984
=> Fix copy in booking confirmation mail

backend/src/appointment/controller/calendar.py
I mainly needed to do another deploy, but it seems like I can't do that manually 😬
=> Tag the caldav host to help debug caldav server errors (Fixes #940)

test/e2e/const/constants.ts, test/e2e/pages/settings-page.ts, test/e2e/tests/settings-general.spec.ts
Add the start of week option to the E2E settings tests.
=> Add start of week setting to E2E tests

test/e2e/const/constants.ts, test/e2e/pages/dashboard-page.ts, test/e2e/tests/settings-general.spec.ts
Follow-up to #1038 (I merged the last PR before pushing these last updates).
=> Add dashboard check in start of week test

backend/requirements.txt, backend/src/appointment/database/repo/subscriber.py
Changelog:
https://github.com/python-caldav/caldav/blob/master/CHANGELOG.md#160---2025-05-30
Seems okay on my end, I upgraded to test something but didn't run into any issues. So should be okay to push up.
=> caldav 1.4.0 -> 1.6.0

backend/src/appointment/database/repo/appointment.py, backend/src/appointment/routes/api.py, backend/src/appointment/routes/schedule.py, frontend/src/components/AppointmentModal.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/stores/appointment-store.ts
This change adds a delete button for expired booking requests to the appointment modal on the bookings overview.
This enables users to clean up a bit.
Closes #1045
=> Expired booking request deletion

backend/src/appointment/controller/apis/zoom_client.py
Removes unnecessary Zoom scope `meeting:update:meeting` as it is blocking our app approval process and we can circumvent the permission scope by deleting and creating a new zoom link.
Unblocks app approval process
https://github.com/thunderbird/appointment/issues/1085
=> Remove Zoom scope meeting:update:meeting

tofu/environments/prod/environment.hcl, tofu/environments/stage/environment.hcl
We have to add a third digit here or the `~>` operator will still allow 3.7.
=> Fix version number

.github/workflows/deploy-staging.yml, pulumi/config.stage.yaml, tofu/environments/stage/environment.hcl, tofu/modules/network/vpc/main.tf, tofu/modules/services/backend-infra/main.tf
This fixes the github workflow automation for merging code. This fixed a number of issues related to the release of new versions of various Terraform providers and modules, restoring the Tofu deploys. It also split Pulumi builds and deploys into new jobs. Further commentary inline.
=> Fix merge automation

.github/workflows/deploy-production.yml
"new_ecr_tag" is not the name of this output.
=> Fix output

pulumi/Pulumi.stage.yaml, pulumi/config.stage.yaml
Phase Three: Move Stage to a Clean Postgres Dataase
=> Move to Postgres in stage

frontend/src/App.vue, frontend/src/components/NavBar.vue, frontend/src/components/NavBarMobile.vue, frontend/src/elements/TextButton.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/AvailabilityView/index.vue, frontend/src/views/FirstTimeUserExperienceView.vue
- Added a NavBarMobile component!
- Design has been approved by the design team for now, except that there might be small tweaks to be done in the near future since the Figma that I've based myself off of is a little outdated already.
- Using `display: none` / `display: show` and separated the Desktop and Mobile navs in their own separate components so that we can avoid using JS window listeners for that and they are significantly different to be together.
- It doesn't receive the `navItems` as props. I see the value of using it before but that was coupling the navigation order and translation file together which gives us less flexibility. For instance, the mobile navigation has a different navigation item order.
- It was very very hard to use Appointment overall without a mobile …
=> Mobile Menu for Appointment

.github/workflows/deploy-staging.yml
Further CI fixes.
CI will hopefully work again.
#1110
=> Fix one more bad file reference
