thunderbird/appointment

frontend/src/components/CalendarQalendar.vue
Fixes #384 
Adds a watch for dayBoundary and forwards the data to qalendar.time. In Qalendar time is created from the config value and is not referenced directly again. So we need to poke at it manually.
It looks a bit silly with one event, but we can adjust that as needed I think!
(Please give it a test 😄 )
=> Watch dayBoundary and forward updates to Qalendar.

frontend/src/components/ScheduleCreation.vue
Fixes #389 
Spotted via a Sentry bug report and then confirmed it was a bug. Easy fix thankfully.
=> Disable the "Generate Zoom Meeting" checkbox if they don't have a zoom account connected.

.github/workflows/deploy-production.yml
Fixed several references to the staging environment from the production environment workflow & enabled passing environment variables to production workflow steps
Production workflow will now correctly run against production terragrunt files
=> fixed incorrect environment references in production workflow

backend/.env.example, backend/src/appointment/controller/calendar.py, backend/src/appointment/dependencies/database.py, backend/src/appointment/routes/api.py
=> if $REDIS_USE_CLUSTER = True then connect to a redis cluster

backend/src/appointment/controller/calendar.py, frontend/src/components/CalendarQalendar.vue
* Google defines all day as "Midnight" to "Midnight + 1 day"
* Subtract 1 minute from the end time.
Fixed:
Sample all day event:
```
{
"11": {
"title": "Test All Day",
"start": "2024-05-10T00:00:00",
"end": "2024-05-11T00:00:00",
"all_day": true,
"tentative": false,
"description": "",
"calendar_title": "<redacted>",
"calendar_color": "#9fe1e7",
"location": null,
"uuid": null
}
}
```
=> Fix all day events bleeding over to following day:

frontend/src/components/ScheduleCreation.vue, frontend/src/views/ScheduleView.vue
This change does two things:
- Extending the preview slots out of the currently shown month for days displayed from the previous/next month
- Keeping calendar events when creating/saving/toggling availability
More convenient display of elements in the calendar on availability configuration.
Closes #350
=> Fix schedule event previews

frontend/.env.prod.example, frontend/.env.stage.example
I forgot I manually built prod while our IaC was being developed. These are safe to be public, I believe it's setup to ignore requests not from our domains.
=> Apply the sentry dsn for frontend builds

tofu/modules/services/backend-infra/main.tf, tofu/modules/services/frontend-infra/main.tf
Some AWS resources require a "https://" prefix while others do not, this trims that prefix where it is not needed
AWS resources requiring the prefix to be removed will launch correctly
=> added trimprefix to frontend_url

README.md, backend/src/appointment/controller/data.py, backend/src/appointment/database/models.py, backend/src/appointment/database/repo/subscriber.py, backend/src/appointment/database/schemas.py, backend/src/appointment/dependencies/auth.py, backend/src/appointment/exceptions/validation.py, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl, backend/src/appointment/migrations/versions/2024_05_31_1454-d5de8f10ab87_add_subscriber_active_flag.py, backend/src/appointment/migrations/versions/2024_05_31_1454-d5de8f10ab87_add_subscriber_soft_delete.py, backend/src/appointment/routes/auth.py, backend/src/appointment/routes/subscriber.py, frontend/src/components/DataTable.vue, frontend/src/definitions.js, frontend/src/views/admin/SubscriberPanelView.vue
This change extends the subscribers model by an active flag and the subscribers panel with buttons for disabling / enabling them.
Also introduces a new data table type `bool` for binary fields.
I added checks for active flag to the login flow, but there must be more places to check for that (maybe even as middleware? I dont know if necessary). @MelissaAutumn Could you add that if needed?
Control over subscribers to quickly ban or reenable them.
Implements a part of #292
=> Soft delete / disabling / enabling subscribers via panel

backend/src/appointment/secrets.py
This should help with AWS credential generation. This will only occur during the aws flow and doesn't affect dev.
=> Ignore the port if it already exists in the host.

README.md, backend/README.md, frontend/README.md
Removed the manual setup (we should be using docker, and fixing that up if it's broken for anyone.) and updated and conslidated some more information.
=> Update the readme

frontend/src/elements/AlertBox.vue
Just a quick additional fix after #469. Forgot to unify the `.alert-close` button too.
#451
=> Unify close button class

backend/deploy.dockerfile, backend/scripts/dummy_setup.py
We remove the setup command from stage/prod dockerfile but this causes an import error. So let's copy over a dummy file for now.
=> Copy a dummy file to prevent import errors

backend/src/appointment/database/models.py, backend/src/appointment/migrations/versions/2024_06_13_1525-e6ed0429ed46_fix_appointment_uuids.py, backend/src/appointment/migrations/versions/2024_06_13_1525-f732d6e597fe_update_appointments_make_uuid_.py, backend/test/unit/test_models.py
* Pass uuid as a callable not a result
* Fix re-create the uuid index to make them unique
* Re-generate all uuids
* Add tests to test uniqueness.
Easy mistake to miss, now fixed and tested.
=> Fix uuids always producing the same result:

frontend/src/router.ts, frontend/vite.config.ts
This change migrates our router.js to TypeScript. Also fixes a bug with the missing resolve filetype `.ts` for vite config.
=> Router TypeScript

frontend/src/composables/dayjs.ts, frontend/src/composables/i18n.ts, frontend/tsconfig.json
This change migrates dayjs and i18n composables to TypeScript. Also this introduces the first custom type.
=> Composables TypeScript

backend/src/appointment/utils.py, frontend/src/views/BookingView.vue
Fixes #500 
This only affects you if you dig into week or day view, but we handle it by removing the hash from the url before we send it up. So this applies it in the booking function.
Also retrieve_user_url_data basically takes `/mel/a6b24d4c/` and splits it into (`mel`, `a6b24d4c`, `/mel/a6b24d4c/`). I'm starting to think we should just split by slash, but that can be another PR.
=> Update regex to allow for spaces and plus signs, and remove the hash before booking.

frontend/src/views/LoginView.vue
Works locally, but sadly our cloudfront rewrite function (https://github.com/thunderbird/appointment/blob/main/tofu/modules/services/frontend-infra/main.tf#L198) doesn't work as well.
=> Remove slash at the start of login calls

.github/workflows/deploy-staging.yml, backend/deploy.dockerfile
I believe this should work. Tested the container side of things locally, without providing one it's an empty env variable, when providing something it fills it in correctly.
=> Bake in the github short sha as the container's release version.

backend/src/appointment/routes/schedule.py
=> Add another except for any OAuth2Errors

backend/src/appointment/database/models.py, backend/src/appointment/database/schemas.py, backend/src/appointment/migrations/versions/2024_07_04_1501-fb1feb76c467_schedule_booking_confirmation.py, backend/src/appointment/routes/api.py, backend/src/appointment/routes/schedule.py, frontend/README.md, frontend/src/components/ScheduleCreation.vue, frontend/src/components/bookingView/BookingViewSuccess.vue, frontend/src/elements/SwitchToggle.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/models.ts, frontend/src/views/BookingView.vue
This change adds a switch to toggle off booking confirmation.
If users don't need the additional layer of safety from flooding their calendar with events, they can make the booking process for potential attendees much faster.
Closes #460
=> Schedule booking confirmation

frontend/.env.example, frontend/vite.config.ts, frontend/vitest.config.ts
Ever since we switched to Vite, my docker container struggles to properly handle hot module reload (HMR), which is a pain for development on my end. I found a configuration for the server section in vite.config.ts which restores HMR for me.
If this doesn't have any known side effects or interference with other configuration, it would improve my dev flow a lot 😇
=> Configuration to fix HMR

backend/src/appointment/migrations/versions/2024_07_04_1501-fb1feb76c467_schedule_booking_confirmation.py, frontend/src/views/BookingView.vue
This is what I get for looking at things and going "eh, that checks out." without manually checking it out.
The migration wasn't working with default, so I swapped it to server_default along with their true() function. Otherwise existing schedules would have this set as false 😱 
And fixed an error from my suggestion that we can't really work-around with the existing store setup. So adding those question marks back in!
=> Use server_default for migrations, and fix a logic error from my suggestion

backend/src/appointment/controller/apis/zoom_client.py
Fixes #546 
Hopefully a fix, I found it's possible that the refresh flow isn't activating properly. The documentation mentions we have to manually handle expires_in, but I guess I assumed the provided expires_at timestamp would handle it automatically. 
It's odd we don't have this issue with fxa, or google oauth though. 
Expires_at isn't in spec, but zoom provides it.
=> Check token for expires_at, and check that against current time and force a refresh if needed.

backend/requirements.txt, backend/src/appointment/database/schemas.py, backend/src/appointment/routes/api.py, frontend/src/main.ts
Fixes #588
I've kept it a separate endpoint in case folks want to block it (We'd rather they not block it, but that's up to them imo.) It requires sentry to be enabled on front and backend.
View:
https://thunderbird.sentry.io/metrics/?interval=30m&project=4505428124827648&statsPeriod=7d
=> Switch page load collection to backend.

frontend/src/components/BookingModal.vue, frontend/src/stores/appointment-store.ts, frontend/test/stores/appointment-store.test.js, frontend/test/stores/calendar-store.test.js
We had an issue where times on all appointments from the appointment store were displayed in the wrong timezone, if the timezone between owner and bookee was different. I think I did that wrong last time I touched this 😅 
Also I removed the "Your booking will be confirmed by the calendar owner." hint from the booking model if confirmation was disabled.
Correct times again.
Closes #542
=> Fix timezone conversion

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Added "terragrunt init -upgrade" ahead of "terragrunt output" commands
Will force Tofu to upgrade the community modules before pulling output.  This should resolve the issue of intermittent provider version errors
=> Fix aws provider issue

frontend/src/components/BookingModal.vue
I can't re-create the problem I saw, but this was the main problem with it. I think it's possible that their tba/user schema was out of date so it was missing accessToken which is what userStore.exists checks explicitly for null. 
Maybe it would be worth versioning our tba/user and any other store data that keeps in local storage. But that's another ticket!
=> Try to avoid filling attendee.timezone with null.

backend/src/appointment/routes/auth.py, backend/test/integration/test_auth.py, frontend/src/views/LoginView.vue
Password based login doesn't work, if username and email differ for a user. This issue was introduced, when the `can-login` endpoint got a check for correct email:
This made logging in via username impossible, when the username isn't a valid email address. To reduce the confusion, I switched to email based login for the password login too.
Email is always the way to go now for both login modes.
None.
=> Fix login if username and email differ

frontend/src/App.vue
This change makes sure we only call metrics if posthog is enabled.
Eliminates a console error.
Closes #598
=> Fix posthog init

frontend/src/App.vue, frontend/src/components/AppointmentModal.vue, frontend/src/components/TabBar.vue, frontend/src/definitions.ts, frontend/src/elements/AppointmentGridItem.vue, frontend/src/elements/calendar/CalendarEvent.vue, frontend/src/keys.ts, frontend/src/router.ts, frontend/src/stores/appointment-store.ts, frontend/src/utils.ts, frontend/src/views/AppointmentsView.vue, frontend/src/views/errors/NotAuthenticatedView.vue, frontend/src/views/errors/RouteNotFoundView.vue
This change adds types for the bookings page and related components.
- The script section was moved to the top in the vue files
- Route `/appointments` now redirects to `/bookings` to match the nav item label and page heading
- Made some name definitions more descriptive
=> Bookings (former Appointments) page TypeScript

frontend/src/components/AppointmentCreatedModal.vue, frontend/src/components/CalendarManagement.vue, frontend/src/components/ConfirmationModal.vue, frontend/src/components/FTUE/GooglePermissions.vue, frontend/src/components/NavBar.vue, frontend/src/components/SettingsAccount.vue, frontend/src/components/SettingsCalendar.vue, frontend/src/components/SettingsConnections.vue, frontend/src/components/SettingsGeneral.vue, frontend/src/definitions.ts, frontend/src/models.ts, frontend/src/stores/calendar-store.ts, frontend/src/stores/external-connections-store.ts, frontend/src/utils.ts, frontend/src/views/CalendarView.vue, frontend/src/views/ContactView.vue, frontend/src/views/HomeView.vue, frontend/src/views/LegalView.vue, frontend/src/views/ProfileView.vue, frontend/src/views/SettingsView.vue, frontend/src/views/WaitingListActionView.vue
This change adds types for the several pages and components, including calendar, contact, home, profile and settings pages.
- The script section was moved to the top in the vue files
- External connections store is now typed with explicitly supported providers
- Several fixes and improvements including removal of deprecated code
=> Calendar, contact, home, profile and settings page TypeScript

frontend/src/components/DataTable.vue, frontend/src/definitions.ts, frontend/src/elements/ListPagination.vue, frontend/src/models.ts, frontend/src/stores/user-store.ts, frontend/src/views/LoginView.vue, frontend/src/views/PostLoginView.vue, frontend/src/views/admin/InviteCodePanelView.vue, frontend/src/views/admin/SubscriberPanelView.vue, frontend/src/views/admin/WaitingListPanelView.vue
This change adds types for the login page, data table and related components.
- The script section was moved to the top in the vue files
- Introduced different types for data table elements
=> Login page and data table TypeScript

frontend/package.json, frontend/src/App.vue, frontend/src/components/DataTable.vue, frontend/src/components/NavBar.vue, frontend/src/components/ScheduleCreation.vue, frontend/src/components/SettingsAccount.vue, frontend/src/components/SettingsCalendar.vue, frontend/src/definitions.ts, frontend/src/elements/TextButton.vue, frontend/src/stores/calendar-store.ts, frontend/src/stores/schedule-store.ts, frontend/src/views/BookingConfirmationView.vue, frontend/src/views/BookingView.vue, frontend/src/views/SettingsView.vue
Adds the following metrics to help guide development resources and priority:
* apmt.copy - Copy to clipboard with a generic uid and label of the button
* apmt.calendar.add - Add a calendar with provider
* apmt.calendar.edit - Edit a calendar with provider
* apmt.calendar.delete - Delete a calendar with provider
* apmt.calendar.connect - Connect a calendar with provider
* apmt.calendar.disconnect - Disconnect a calendar with provider
* apmt.calendar.sync - Sync your calendars with old and new calendar counts
* apmt.account.refreshLink - Refresh your booking link
* apmt.account.download - Download your account data
* apmt.account.deleteAccount - Delete your account
* apmt.booking.confirm - Confirmed a booking request
* apmt.booking.deny - Denied a booking request
* apmt.booking.request - …
=> Additional metrics

backend/src/appointment/controller/mailer.py, backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl, frontend/src/locales/de.json, frontend/src/locales/en.json
This change modifies the EN date format (adds a `,` between day and year) and catches up all DE locales to recent changes.
Improved language
#612
=> Language improvements

backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/en/email.ftl, backend/src/appointment/templates/email/confirm_email.jinja2, frontend/src/components/GenericModal.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/LoginView.vue, frontend/src/views/WaitingListActionView.vue
Finishes off #579 
...I'm sorry for the amount of l10n work needed.
=> Login Re-work Pt2

backend/requirements.txt, backend/src/appointment/exceptions/validation.py, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl, backend/src/appointment/main.py, backend/src/appointment/routes/schedule.py, backend/src/appointment/routes/waiting_list.py, backend/test/integration/test_waiting_list.py, frontend/README.md, frontend/src/models.ts, frontend/src/views/LoginView.vue
Fixes #466 
Rules:
* waiting-list/join - 2/minute
* schedule/public/availability - 10/minute
* schedule/public/availability/request - 10/minute
I think we could reduce the request one to like 2 or 3, but it's not really a concern right now. Mostly just preemptively avoiding spam. I didn't hook it up with redis because I don't think we have redis setup correctly on prod yet. Shouldn't be a problem for us right now though. 
It works off of remote ip address, I think that's probably okay.
=> Add slow api rate limiting

frontend/src/components/CalendarQalendar.vue, frontend/src/stores/appointment-store.ts
- List of pending events on the calendar page now only shows future pending events (which reduces the list to a reasonable length, but let me know if this not wanted)
- First day of week is now locale aware (Monday for German, Sunday for English). In a future iteration this should be a user setting keeping these as defaults.
- I tried to fix #544 and spent quite some time debugging Qalendar for this. It turns out, that it's an issue with computed / reactive properties and Qalendar not updating their UI accordingly.
Consistent height of events after a change of the day boundary.
#544
=> Qalendar fixes

tofu/modules/services/backend-service/main.tf
Added a conditional to launch two backend containers on prod but maintain a single container in non-prod environments
increases reliability of production environment while maintaining minimum costs in non-prod
resolves #674
=> added conditional to determine # of backend containers

tofu/modules/services/backend-service/main.tf
Adds a second backend container to stage to verify IaC before prod deployment
redundant container in the event one has issues
=> actually added second container to stage

backend/src/appointment/controller/apis/zoom_client.py, backend/src/appointment/controller/zoom.py, backend/src/appointment/database/repo/external_connection.py, backend/src/appointment/dependencies/zoom.py, backend/src/appointment/routes/webhooks.py, backend/src/appointment/routes/zoom.py, backend/src/appointment/secrets.py, backend/test/integration/test_webhooks.py
Fixes #680 
Deauthorization webhook as described here: https://developers.zoom.us/docs/platform/auth/deauthorization/
New scopes are as-is in the Zoom app. 
Works locally, but the development/beta login links require development changes to remove state (hence my revert when I accidentally included the test changes in an earlier commit lol)
=> Zoom Updates

frontend/src/definitions.ts, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/models.ts, frontend/src/stores/user-activity-store.ts, frontend/src/views/ScheduleView.vue
Fixes #684
...ignore the branch number, I'm not sure how I messed it up that bad.
Needs German strings!
=> Add a beta warning warning people about the fact we're still in beta.

frontend/src/components/DataTable.vue
Fixes #689 
I think I may have overcomplicated the solution but I can't think of a better solution right now. 
Basically we need to re-apply all the filters if a filter changes, and we also need to store state of the current filters somehow. As they're a dynamic object we can just store in an object.
=> Re-apply each filter on filter change for data tables.

frontend/src/components/ScheduleCreation.vue, frontend/src/tbpro/elements/BubbleSelect.vue, frontend/src/tbpro/elements/TextInput.vue
- Add the ability to be disabled for BubbleSelect
- Fix the quick link field to get disabled on schedule deactivation
I also added the changes to a corresponding PR in services-ui:
https://github.com/thunderbird/services-ui/pull/4
Closes #686
=> Fix weekday selection and quick link to get disabled

backend/src/appointment/controller/mailer.py, backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/en/email.ftl, backend/src/appointment/templates/email/confirm.jinja2, backend/src/appointment/templates/email/errors/zoom_invite_failed.jinja2, backend/src/appointment/templates/email/includes/base.jinja2, backend/src/appointment/templates/email/new_account.jinja2, backend/src/appointment/templates/email/new_booking.jinja2
This change extends the base email template by a section above the email footer containing a hint with a link to the contact form and how to get support.
It can be enabled in email templates by setting:
```jinja
{% set show_contact_form_hint = True %}
```
It was enabled in the following templates:
- Email to confirm a booking request
- Email that a zoom invitation failed
- Email for account invitation
- Email for new booking information
Info for users where/how to get help/support.
Closes #642
=> Add contact form hint to mails

frontend/src/components/ScheduleCreation.vue, frontend/src/tbpro/elements/SwitchToggle.vue
- Booking confirmation is now properly handled via schedule input object. This fixes a bug where a direct call on the retrieved schedule object happend on null.
- The SwitchToggle component now handles state changes from the parent. This sometimes happens during initialization when waiting for async data.
Fixes #695
=> Fix booking link toggle in schedule creation

backend/src/appointment/controller/calendar.py
Fixes #696 
The fix is only applied to the google calendar connector because we don't actually of a method of determining which attendee is the calendar owner. (As they could technically have no email associated with a caldav calendar...) This will hopefully be cleared up with the freebusy api.
=> Filter out declined for Google Events

frontend/src/components/ScheduleCreation.vue
Fixes #705 
Originally we used state because v-model wasn't working. Now it works, so uhh. I moved it back.
=> Swap the :checked state to a v-model that applies on change event.

frontend/src/components/ScheduleCreation.vue, frontend/src/locales/de.json, frontend/src/locales/en.json
This changes the "Clear form" button label to "Revert changes" on schedule creation / modification.
Closes #701
=> Fix language on schedule creation

README.md, backend/.env.example, backend/README.md, backend/src/appointment/database/models.py, backend/src/appointment/database/schemas.py, backend/src/appointment/migrations/versions/2024_10_08_1615-502d0217a555_add_timezone_to_schedule.py, backend/src/appointment/routes/auth.py, backend/test/factory/schedule_factory.py, backend/test/integration/test_auth.py, frontend/src/components/FTUE/SetupSchedule.vue, frontend/src/components/ScheduleCreation.vue, frontend/src/models.ts, frontend/src/views/LoginView.vue
Part of #120 
This allows the password flow to create a new subscriber on first-login. But only first-login. (Well when there's no subscribers.) 
Input wanted: Do we need to put this behaviour behind a env flag for extra security? 
I discovered a fun bug with schedule creation/updates that causes it to fail because times are in UTC and 14:00 as a start-time is bigger than 0:00 as an end time. So we now collect timezones for schedules, and store them. (That'll be handy later!) We don't do anything else with them right now.
=> Password Login Fixes

frontend/src/components/GenericModal.vue, frontend/src/views/WaitingListActionView.vue
This PR adds event handling for a `close` emit from the GenericModal.
Close buttons on the waiting list modal will work now.
Closes #719
=> Handle generic modal close event

tofu/modules/data-store/database/main.tf
AWS auto-upgraded the MySQL database's minor version. This PR adjusts our code to match the version.
Deploys, which currently throw this error...
```
Error: updating RDS DB Instance (tb-apmt-prod): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 56ae8219-9792-451c-a05b-a15fdc6c5241, api error InvalidParameterCombination: Cannot upgrade mysql from 8.0.35 to 8.0.32
```
...will no longer fail.
Related to errors noticed in [this job](https://github.com/thunderbird/appointment/actions/runs/11463482722/job/31897432138).
=> Upgrade MySQL minor version

frontend/src/components/ScheduleCreation.vue
The button for updating the quick link slug is now grayed out and inactive, as soon as the schedule becomes inactive.
Closes #686
=> Disable quick link update on inactive schedules

frontend/src/definitions.ts, frontend/src/models.ts, frontend/src/stores/calendar-store.ts, frontend/src/stores/schedule-store.ts, frontend/src/views/ScheduleView.vue
This PR aims to improve performance of the dashboard (Schedule configuration page). The already existing schedule store got hooked up on the dashboard page. Still misses:
The dashboard now retrieves events per month, only if that month is navigated to the first time. The events will be remembered from this point making calendar navigation much faster and more convenient, when returning to views/months already visited.
Closes #648
=> Schedule page stores

tofu/modules/services/backend-service/main.tf
Increases backend container size in prod to 1vcpu/4GB while keeping stage on 0.5vcpu/1GB
More resources to support increased user base as we expand the beta
=> increased container size in prod

backend/src/appointment/routes/schedule.py, backend/test/unit/test_utils.py
Fixes #735 
Fixes a case where the date could overflow to a day of the week which the schedule has disabled. Which would fail booking slot validation. 
This is because days of the week are saved based on the user/schedule's timezone rather than UTC. Which is a little confusing and we should maybe look into fixing that, but this is a quick fix for now.
=> Validate booking slot's weekday in schedule timezone. (Fixes #735)

backend/src/appointment/controller/calendar.py, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl
This change ignores all remote events, that don't have a `dtstart` or neither a `dtend` nor `duration`. Also the event title gets a default value, if `summary` is missing.
Wider range of supported caldav servers.
Fixes #741
=> Handle missing vevent attributes

backend/src/appointment/controller/calendar.py
This adds exception handling for caldav PropfindErrors.
Fixes #748
=> Handle PropfindError exception

backend/src/appointment/controller/apis/google_client.py, backend/src/appointment/controller/calendar.py, backend/src/appointment/database/models.py, backend/src/appointment/database/repo/appointment.py, backend/src/appointment/database/repo/slot.py, backend/src/appointment/database/schemas.py, backend/src/appointment/exceptions/calendar.py, backend/src/appointment/exceptions/validation.py, backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl, backend/src/appointment/migrations/versions/2024_11_26_2209-d791a3f0e478_add_external_id_to_appointments.py, backend/src/appointment/routes/schedule.py, backend/src/appointment/tasks/emails.py, backend/test/conftest.py
This change implements the [previously discussed](https://github.com/thunderbird/appointment/issues/459#issuecomment-2492915805) hold event flow.
This still needs heavy testing for both: Google and CalDAV.
Fixes #459
=> Hold invites

backend/src/appointment/controller/mailer.py
Should fix #773 
I can't really test it in thunderbird, but the header shows up in mailpit. 
I'm not sure if there's a better way to fix this header, the python api seems a little...light on implementation details outside of "Hey add an attachment to an email and send it!" 🤔
=> Replace the content-type on ics files

backend/src/appointment/controller/calendar.py, backend/src/appointment/controller/mailer.py, backend/src/appointment/routes/schedule.py, backend/src/appointment/tasks/emails.py
This change adds an attachment to the email that informs the user, that their booking got rejected. This enables the user to simply click delete and update their calendar to remove the hold event.
Closes #775
=> Declined booking event handling

backend/src/appointment/controller/calendar.py, backend/src/appointment/l10n/de/email.ftl, frontend/src/components/SettingsCalendar.vue, frontend/src/definitions.ts, frontend/src/locales/de.json, frontend/src/locales/en.json
This change improves the setup of new CalDAV connections.
- Form fields are now validated and provide browser validation messages
- CalDAV creds are now validated with error/success message
- On success, the available calendars are automatically displayed
Better feedback for users on CalDAV setup in settings.
Closes #777
=> Improve caldav calendar settings flow

README.md, frontend/src/components/NavBar.vue, frontend/src/views/LoginView.vue, test/e2e/.env.example, test/e2e/.gitignore, test/e2e/README.md, test/e2e/browserstack.yml, test/e2e/const/constants.ts, test/e2e/package-lock.json, test/e2e/package.json, test/e2e/pages/dashboard-page.ts, test/e2e/pages/fxa-page.ts, test/e2e/pages/splashscreen-page.ts, test/e2e/playwright.config.ts, test/e2e/tests/sign-in.spec.ts, test/e2e/tests/splashscreen.spec.ts, test/e2e/tsconfig.json
This PR adds a `production sanity` E2E test which verifies the splashscreen appears, and we are able to sign-in to Appointment production. The suite can be run on your local machine against locally-installed browsers or against browsers located in the BrowserStack Automate cloud platform.
For more details please see the included `/test/e2e/README` file. If you want to try running the tests in BrowserStack and don't have a BrowserStack account yet let me know and I can get you set up :)
=> (#490) Add an automated production sanity test

backend/src/appointment/controller/mailer.py, backend/src/appointment/l10n/de/email.ftl, backend/src/appointment/l10n/en/email.ftl, backend/src/appointment/templates/email/confirm.jinja2, backend/src/appointment/templates/email/errors/zoom_invite_failed.jinja2, backend/src/appointment/templates/email/includes/base.jinja2, backend/src/appointment/templates/email/invite.jinja2, backend/src/appointment/templates/email/new_account.jinja2, backend/src/appointment/templates/email/new_booking.jinja2
This PR changes the default _reply-to_ (configured system or support email address) for the invitation mail (x has accepted your booking) and the new booking mail (x has just booked...).
The configuration is now like this:
- invitation mail (_... has accepted your booking_)
- To: Bookee
- Reply-To: Owner
- new booking mail (_... has just booked..._)
- To: Owner
- Reply-To: Bookee
Closes #765
=> Add owner email as reply-to header

frontend/src/components/ScheduleCreation.vue
Turns out props.calendars is an array not an object!
Closes #758
=> Fix the selected calendar on the Dashboard schedule component. (Fixes #758)

.github/workflows/deploy-production.yml, .github/workflows/nightly-tests.yml
Add a new GHA `nightly-tests` workflow which will run the Appointment production sanity test every night at 1AM UTC / 8PM EST via BrowserStack. It will be good to have the sanity test run once per day regardless on if there are any deployments; this will ensure any test issues or breaks will be caught ASAP and not at deployment time.
Also modifying the existing `deploy-production` workflow so that this same production sanity test will run automatically after each production deployment is completed.
Example of the nightly-tests.yml workflow running and working - the tests ran successfully in BrowserStack:
https://github.com/thunderbird/appointment/actions/runs/12400284448/job/34617094382
(See comment below for corresponding screenshots).
=> Add production sanity test to CI

backend/src/appointment/routes/schedule.py, backend/test/integration/test_schedule.py
This PR adds a check for slot status before confirming or rejecting a booking request.
Prevents booking requests from being answered multiple times, each time sending a confirmation/rejection email to the bookee.
Closes #791
=> Check for slot status before confirming or rejecting a booking request

backend/src/appointment/routes/auth.py, backend/test/integration/test_auth.py, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/LoginView.vue
Instead of displaying raw json or text, we now redirect them back to the login page with an error code. That error code is used to look up a proper error message.
This removes the confusing "Email mismatch" message and a few others.
cc @malini for copy check.
=> Replace HttpExceptions with RedirectResponses with login err codes. (Fixes #801)

backend/src/appointment/controller/calendar.py, backend/src/appointment/exceptions/calendar.py, backend/src/appointment/exceptions/validation.py, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl, backend/src/appointment/routes/caldav.py, frontend/src/tbpro/elements/NoticeBar.vue
This hopefully gives the user a little more feedback on what went wrong with their connection attempt.
=> Adjust CALDAV.test_connection to return a boolean or raise an exception with a message. (Fixes #802)

backend/src/appointment/controller/mailer.py, backend/src/appointment/database/models.py, backend/src/appointment/database/schemas.py, backend/src/appointment/l10n.py, backend/src/appointment/middleware/l10n.py, backend/src/appointment/migrations/versions/2024_12_18_1226-b398005a40e7_add_language_to_subscriber_table.py, backend/src/appointment/migrations/versions/2024_12_20_1733-0c99f6a02f3b_make_subscribers_language_not_.py, backend/src/appointment/routes/api.py, backend/src/appointment/routes/schedule.py, backend/src/appointment/tasks/emails.py, backend/src/appointment/templates/email/confirm.jinja2, backend/src/appointment/templates/email/includes/base.jinja2, backend/src/appointment/templates/email/includes/footer.jinja2, backend/test/conftest.py, backend/test/unit/test_mailer.py, docs/README.md
This PR adds a new field `language` for the subscribers table and extends our l10n middleware for using a custom locale.
The tests were adjusted and extended accordingly.
Subscribers should see emails sent to them in their configured language now.
Closes #766
=> Add subscriber language and localize emails

backend/src/appointment/database/repo/appointment.py, backend/src/appointment/database/repo/calendar.py, backend/src/appointment/database/repo/external_connection.py, backend/src/appointment/database/repo/schedule.py, backend/src/appointment/database/repo/slot.py, backend/src/appointment/database/schemas.py, backend/src/appointment/routes/schedule.py
Migrating our current class-based model config to [ConfigDict](https://docs.pydantic.dev/2.10/api/config/#pydantic.config.ConfigDict). Also use `json_schema_extra`. Also use `.model_dump()` instead of `.dict()`.
No more deprecation warnings. Hopefully.
Closes #783
=> Migrate class-based config to ConfigDict

backend/src/appointment/database/models.py, backend/src/appointment/database/schemas.py, backend/test/integration/test_schedule.py, frontend/src/components/ScheduleCreation.vue
#778 
This should fix the incorrect endtime displayed in the schedule time validation error message. The backend was incorrectly returning it as a non-UTC time which then the frontend used to convert it from UTC to the schedule's timezone. (So double conversion.)
This should also fix an issue with daylight savings and this error message by always saving the current date as the start_date, as we don't actually expose that value to the end-user. (And it's used for daylight savings conversion.)
And finally I've adjusted the schedule creation test to use a timezone, and to use pacific time-converted values for the time so it's actually accurate. 
cc @rwood-moz
=> Fix incorrect endtime in schedule validation message (Fixes #778)

backend/src/appointment/commands/generate_documentation_pages.py, backend/src/appointment/routes/commands.py, docs/zoom/en/using-zoom.md, frontend/src/assets/docs/en/using-zoom.html, frontend/src/router.ts, frontend/src/views/DocsView.vue
Added a new command based off the download-legal command that generates html pages from local docs. Currently we only need this for zoom because of their verification requirements but we can use it for other pages in the future.
The markdown pages are separated by language/locale right now, I don't think we need a German version of this page just yet though. We should wait until we confirm copy is okay, and Zoom accepts it.
This has to be on appointment.day as per the [guidelines](https://developers.zoom.us/docs/build-flow/prep-app-for-prod/#link--support) of the zoom verification process.
cc @malini
=> Add a process to generate html from local md files and create a docs route for zoom

.github/workflows/deploy-production.yml, .github/workflows/nightly-tests.yml, test/e2e/browserstack.yml, test/e2e/package.json
Currently when the production sanity test is ran via github actions, the same browserstack build name is used each time (every test run is added to the same browserstack Automate build). This change updates the test configuration so that we will have a separate browserstack build for each time the test runs. See comment below for new screenshots from BrowserStack.
=> Fix browserstack session name

backend/requirements.txt
This PR just upgrades sentry-sdk from 2.10.0 to 2.20.0.
This seems to fix issues on calling `sentry_sdk.capture_exception(e)`.
Closes #825
=> Upgrade sentry-sdk

backend/test/integration/test_account.py, backend/test/integration/test_appointment.py, backend/test/integration/test_auth.py, backend/test/integration/test_calendar.py, backend/test/integration/test_general.py, backend/test/integration/test_invite.py, backend/test/integration/test_profile.py, backend/test/integration/test_schedule.py, backend/test/integration/test_subscriber.py, backend/test/integration/test_waiting_list.py
I analyzed the existing integration tests against the backend API (and created [this google sheet](https://docs.google.com/spreadsheets/d/1tbfXML-FsBRns_ayibhf6R_uHbTL_pWDGTJpRdldMdI/edit?usp=sharing)). This PR adds new integration tests to expand test coverage and fill in some of the gaps that I noticed. Sorry it's a bit of a larger PR than I had originally anticipated.
I tested by running all of the tests locally (and also they're green in CI on this PR's related `validate-backend` checks).
=> Expand the integration tests

backend/src/appointment/controller/mailer.py
Fixes #816 
Previously Condition-Disposition was being set to attachment because we named the file. But we want it as an inline file, so don't name the file.
=> Don't name inline attachments. (Fixes #816)

.github/workflows/validate.yml, backend/.coveragerc, backend/README.md
Enable code coverage analysis (for the backend tests) both when running the tests locally as well as in CI. See the updated README file for more information.
Thanks @MelissaAutumn as you already had the groundwork for this in the repo! I am just updating the README and enabling the code coverage tool to run in CI.
=> Enable code coverage analysis locally and in CI

.github/workflows/deploy-production.yml, .github/workflows/nightly-tests.yml, test/e2e/.env.example, test/e2e/.gitignore, test/e2e/README.md, test/e2e/browserstack.yml, test/e2e/const/constants.ts, test/e2e/package-lock.json, test/e2e/package.json, test/e2e/pages/booking-page.ts, test/e2e/pages/dashboard-page.ts, test/e2e/pages/splashscreen-page.ts, test/e2e/playwright.config.ts, test/e2e/tests/book-appointment.spec.ts, test/e2e/tests/sign-in.spec.ts, test/e2e/tests/splashscreen.spec.ts, test/e2e/utils/utils.ts
Add the following scenarios to the production sanity playwright E2E test:
- able to access the booking page via short link
- able to access the booking page via long link
- able to request a new booking
Here is a link to the new [updated test running via GitHub actions](https://github.com/thunderbird/appointment/actions/runs/12682709711) on this branch.
And here is the corresponding [recorded video of the test running in BrowserStack](https://automate.browserstack.com/dashboard/v2/builds/5a013832e5e5a6887bd38c4c95a293087035b9aa/sessions/a82f4bd488bd554f38515e4b949676952b98695c) (if you need BrowserStack credentials just let me know and I can set you up!).
=> Expand the production sanity test

.github/workflows/validate.yml, backend/pyproject.toml
This PR does a few things:
- Adds a frontend ESLINT `npm run lint` linting step in the GHA frontend validation 
- Adds a backend `ruff check` linting step in the GHA backend validation
- Adds a frontend build step (`npm run build`) during the frontend GHA validation as previously the frontend tests were run but no actual build was done, so build errors were not caught
**Note: Once this lands, the GHA validate job will start failing if there are linting errors. Therefore my other PRs must land first (which fix existing lint errors): #836  and #843.**
=> Enable linting in CI, and add frontend build step in validate

test/e2e/const/constants.ts, test/e2e/pages/dashboard-page.ts, test/e2e/playwright.config.ts, test/e2e/tests/book-appointment.spec.ts
The production sanity E2E test failed because of a couple of issues related to end-of-month:
- Since there were no slots left at the end of January the request booking page automatically displays February, even though the current month is still January (makes sense); however the test was expecting the request booking page header to be the current month of January. Update the test to accept either the current month or next month in the request booking page header.
- When the test signs into the host account to verify a hold appointment was created at the correct time slot, the current month (January) was displayed however the appointment was actually created for February since no slots were left in January. The test should have automatically skipped forward to February (since the hold …
=> Fix production sanity test end-of-month issues

backend/src/appointment/database/models.py, backend/src/appointment/database/schemas.py, backend/src/appointment/migrations/versions/2025_02_11_1254-330fdd8cd0f8_modify_subscribers_table.py, frontend/index.html, frontend/src/utils.ts
This PR fixes a bug, were the user setting for the time format didn't apply correctly. Also, h12 is set now as a new default.
> [!TIP]
> I already took PR #854 into account for db migrations, although it is not merged yet.
Closes #850
=> 12h default time format

backend/README.md, backend/src/appointment/controller/mailer.py
This PR fixes indices of inline images in the invitation email. Maybe for the future it's better to work with dictionary keys instead of positional list keys for attachements.
Fixes a broken icon image.
Closes #856
=> Fix inline icons in invitation email

frontend/src/components/bookingView/BookingViewSuccess.vue
It's now legible, unlike the light mode I used a different background colour because the drop shadow is less noticable on dark mode.
=> Tweak dark mode colours on the booking success screen (Fixes #864)

frontend/.env.example, frontend/.env.prod.example, frontend/.env.stage.example, frontend/src/utils.ts
Should fix this right up and allow folks to override this on a self-hosted install.
=> Fallback to `VITE_DEFAULT_HOUR_FORMAT` if the browser doesn't provide a time format. (Fixes #867)

.github/workflows/deploy-production.yml, .github/workflows/nightly-tests.yml, test/e2e/.env.prod.example, test/e2e/README.md, test/e2e/const/constants.ts, test/e2e/pages/booking-page.ts, test/e2e/pages/fxa-page.ts, test/e2e/pages/splashscreen-page.ts, test/e2e/utils/utils.ts
In order to allow the E2E tests to run on environments other than production, the first step is to rename the environment variables to be generic (remove `prod` references) and also make a new `.env.prod.example` env vars file. This will clear the way to add more supported environments (i.e. stage).
=> Remove references to prod in env var names

backend/src/appointment/controller/mailer.py, backend/src/appointment/templates/email/includes/base.jinja2, frontend/.env.example, frontend/.env.prod.example, frontend/.env.stage.example, frontend/src/components/ExternalRedirect.vue, frontend/src/components/NavBar.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/views/ContactView.vue, frontend/src/views/ReportBugView.vue
Fixes #872 
This also removes the reply-to header for support emails, and replaces it with a link to our contact form. (Which now redirects to zendesk.)
=> Add Zendesk Link

frontend/src/locales/en.json
Quick change fixing a typo in one of the UI messages. "Information" is usually an uncountable noun in English, including in this case.
Minor improvement in user experience
N/A
=> Fix grammatical mistake in frontend English messages

backend/src/appointment/controller/data.py, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl
While trying out the `download your data` feature I noticed the downloaded data readme is out of date, and the files are not named consistently (some are plural and some aren't). Update the readme and change the name of some of the data csv files so they are more consistent.
Here are the resulting csv files downloaded:
=> Update the download data readme and make filenames consistent

frontend/src/components/CalendarQalendar.vue
This PR fixes the mini-calendar popup in week view to respect the content width again.
Prevent content bleeding.
Closes #886
=> Fix calendar popup width in week view

frontend/src/App.vue, frontend/src/views/ScheduleView.vue
This PR fixes an issue, where overflowing contents in the schedule creation sidebar were hidden behind adjacent elements. This happened because of reversed overlapping priority due to reversed flex items and got fixed by setting a z-index.
This also fixes another linter warning in App.vue.
Overlapping should show again.
Closes #887
=> Fix tooltip in schedule creation sidebar

.github/workflows/validate.yml, backend/README.md
Update the GHA validate workflow so that when the E2E test source itself changes, the E2E tests should be run as part of the PR checks.
Also a small backend README correction.
=> Run E2E tests in CI when E2E test source changes

backend/src/appointment/database/models.py, backend/src/appointment/routes/caldav.py, backend/src/appointment/routes/schedule.py, backend/test/conftest.py, backend/test/factory/schedule_factory.py, backend/test/integration/test_schedule.py, backend/test/integration/test_subscriber.py, backend/test/unit/test_utils.py
Fixes #919 
This took a bit of thinking. But we can't actually calculate the time in UTC as the stored schedule start/end time is in UTC from potentially a different offset than the incoming booking start/end time.
So lets transform these all to local time and do the comparison. We have the intended start/end time's offset from when the schedule was last saved, so we can use that to transform 17 back to 9, and today's offset can be used to transform 16 to 9. 
I've also adjusted the test subscriber's timezone to default to America/Vancouver, and updated some tests.
=> Timezone offset issue

backend/src/appointment/database/repo/subscriber.py, backend/src/appointment/migrations/versions/2025_03_07_2109-537672c3933d_data_migration_clean_up_email_.py, backend/src/appointment/routes/api.py, backend/src/appointment/routes/auth.py, backend/src/appointment/routes/google.py, backend/src/appointment/routes/subscriber.py, backend/src/appointment/routes/waiting_list.py, backend/src/appointment/routes/webhooks.py, backend/test/integration/test_auth.py, backend/test/integration/test_waiting_list.py, backend/test/integration/test_webhooks.py
(Fixes #914)
This isn't as the name implies actually a quick fix, but I find it a little silly slapping to .lower() in a bunch of places. If anyone else has a good idea on centralizing this step I'm all ears! (Likewise for additional test cases.)
But this should resolve any outstanding email casing issues.
=> Add data migration to lowercase emails, and only ingest lowercase emails.

.github/workflows/deploy-staging.yml, .github/workflows/validate.yml
Only run the E2E tests on stage after stage deployments; no point in running them after PR/branch updates because the branches themselves aren't being deployed to stage until after they're merged to main anyway. More info in #922.
=> Run E2E tests on stage only after stage deployments

backend/src/appointment/database/schemas.py
I didn't get this error until now...odd. But this prevents it from recursively calling the relationships...oops.
This change pulls in some of schema.Subscriber keys without pulling in the relationships to calendars and slots that we don't need in this context.
=> Don't include relationships for the Subscriber admin item

backend/src/appointment/routes/subscriber.py, backend/test/integration/test_subscriber.py, frontend/src/views/admin/InviteCodePanelView.vue, frontend/src/views/admin/SubscriberPanelView.vue, frontend/src/views/admin/WaitingListPanelView.vue
get_by_email now does searches on lowercase emails only, so we can't delete a mixed-case user lol!
This should have been using ids from the start anyway. 
Additionally I've added in a quick search textbox to help find emails faster (or invite codes)
=> Disable/Enable Routes Should Use ID (Fixes #932)

backend/src/appointment/database/models.py
To help debug issues in the future with random errors. Just ids for now. 
Instead of showing `<appointment.database.models.Subscriber object at $pointer_address>` it should show something like `Subscriber: 15`.
=> Add string representation to models, so we can at least get their ids.

.github/workflows/deploy-staging.yml
Fix the `e2e-tests-browserstack-stage` job (within the `deploy-staging.yml` GHA workflow). Remove the IF condition and run the tests every time a release has been created.
Fixes #950
=> Fix GHA E2E stage test job

backend/Dockerfile
Removing developer used line from main code (thus assumable production code, once out of beta)
First time container builder reason: Yes, it echos that .env needs to be made, but this allows a successful build immediately upon cloning the repo, and more importantly..
Image/infrastructure security reason: The .env file should not be built in to the image, as one can take the image and pull the password out if anyone ever uploads an image for public pulling. This is especially true, since the docker-compose file utilizes the .env file on the host system, not on the container, anyway.
Removing it from the Dockerfile prevents many possible future accidents.
Leaving them commented, rather than removed still allows for an easy change by devs if they want these lines.
Working on designing a …
=> Unique .env files shouldn't be added to container images

frontend/src/components/CalendarManagement.vue, frontend/src/components/SettingsCalendar.vue, frontend/src/components/SettingsConnections.vue, test/e2e/README.md, test/e2e/const/constants.ts, test/e2e/package-lock.json, test/e2e/pages/booking-page.ts, test/e2e/pages/dashboard-page.ts, test/e2e/pages/settings-page.ts, test/e2e/pages/splashscreen-page.ts, test/e2e/playwright.config.ts, test/e2e/tests/book-appointment.spec.ts, test/e2e/tests/settings.spec.ts, test/e2e/tests/sign-in.spec.ts, test/e2e/utils/utils.ts
Add E2E tests to exercise the Appointments settings. These additional tests will run as part of the E2E suite that runs locally as well as on stage per PR. Also adds some `data-testid` attributes to some of the front-end elements to make it easier for the tests to find them.
Also some general test improvements:
- Removing the waits for `domcontentloaded` when navigating to pages because playwright automatically waits for the page load event (which is the entire page, not just the domcontent)
- Added constants for timeout values
For more information on how to run these tests please see the [/test/e2e/README](https://github.com/thunderbird/appointment/blob/main/test/e2e/README.md).
=> Add E2E tests for settings

test/e2e/README.md, test/e2e/tests/book-appointment.spec.ts, test/e2e/tests/settings.spec.ts
Ensure the playwright browser context timezone is set for the E2E tests (fixes #957).
Also one of the settings tests (download data) fails when running in BrowserStack because BrowserStack doesn't support the `download.path` playwright method; so fixing that too.
```
Error: Path is not available when connecting remotely. Use saveAs() to save a local copy.
294 |     // now verify the browser download did happen successfully
295 |     const download = await downloadPromise;
> 296 |     const downloadedPath = await download.path(); // waits for download to finish
```
Here's a [link of the updated tests ](https://automate.browserstack.com/dashboard/v2/builds/ba55998a9a17f973261692be5995fa087b1a6004)running successfully on stage via BrowserStack in both Firefox and Chromium.
=> Set the E2E test browser context timezone and fix download test

frontend/src/components/ScheduleCreation.vue, frontend/src/components/SettingsAccount.vue, frontend/src/locales/de.json, frontend/src/locales/en.json
This PR changes the slug changed confirmation modal from showing when clicking the refresh button to clicking the save button. The confirmation appears only, if the slug was changed manually or per refresh button.
Uses get warned even if they manually edited their link.
Closes #903
=> Slug change confirmation

.github/workflows/validate.yml, backend/src/appointment/controller/auth.py, backend/src/appointment/dependencies/auth.py, backend/src/appointment/utils.py
Related #969 
This is just for staging right now. Based off the sentry data the user's minimum time is one second after issued at time. The only thinig that sets the minimum time is the webhooks. So I guess the webhooks are getting fired off after we ask them to destroy a token. If someone logs in just at the right time, they can be immediately logged out lol.
Neither systems are long for this world, so hopefully this reduces the issue until we switch auth over.
=> Hopeful fix for being logged out after logging in

test/e2e/pages/settings-page.ts, test/e2e/tests/settings.spec.ts
A couple of small updates to the E2E settings tests:
- For the edit calendar settings test, click the cancel button instead of save (as there is an issue where caldav settings appears briefly before google calendar settings; I created issue #977 for that)
- Add a small timeout for the delete account button test (need time for the delete confirmation to appear before clicking cancel)
=> Small update to E2E settings tests

.github/workflows/nightly-tests.yml, test/e2e/README.md, test/e2e/const/constants.ts, test/e2e/package.json, test/e2e/playwright.config.ts, test/e2e/tests/book-appointment.spec.ts, test/e2e/tests/settings.spec.ts, test/e2e/tests/sign-in.spec.ts, test/e2e/tests/splashscreen.spec.ts
Currently only the production sanity E2E test runs nightly; expand the nightly E2E test job (runs on production) to include the newly added settings tests too.
=> Expand nightly E2E tests job to include all tests

backend/src/appointment/dependencies/auth.py, backend/test/integration/test_auth.py, frontend/src/stores/user-store.ts
Fixes #969 
The current login flow is expected to work like this:
```mermaid
flowchart TD
A[FXA Login] -->|Redirect| B[APMT Backend - /fxa]
B -->|Redirect| C[APMT Frontend - /post-login/:one-time-token]
C -->|API Call using one-time-token as auth| D[APMT Backend - /fxa-token]
D -->|Returns longer-lived token| E[APMT Frontend]
E -->|Uses longer-lived token| F[APMT ...rest of the app...]
```
We have a one time token that is returned, and then swapped for a longer lived token. This is so if anyone is snooping on urls they won't be able to do much with that token, as the token is returned in the redirect to post-login in the url. (Not much we can do here without sessions afaik.) 
However, that one time token can be used for any request...which obviously isn't great. This PR adds another check …
=> Don't use one time access token for every request (Fixes #969)

test/e2e/playwright.config.ts, test/e2e/tests/book-appointment.spec.ts, test/e2e/tests/settings.spec.ts
Some E2E test improvements:
- Add/update Playwright E2E timeouts so that when there are test failures the tests will fail out faster (and not hold up the queue of BrowserStack jobs)
- A couple of tests fail when run against the local dev environment b/c they are only meant for stage/prod; exclude them on local dev
Here's an example of the tests [running in BrowserStack](https://automate.browserstack.com/dashboard/v2/builds/63bacda3c38b93800ab495575afbb1395c7e3e2c) with this new timeouts added.
=> Improve E2E test timeouts

backend/src/appointment/controller/apis/zoom_client.py
Fixes #996 
I'm not sure why they hate having scopes in the url, since our third-party oauth library does it for us. So it's within spec, but at least it doesn't seem to affect our meeting link creation abilities. 
Tested and working fine locally.
=> Don't pass our scopes to the zoom auth url (Fixes #996)

tofu/modules/data-store/database/main.tf
Ah the real cause of the failed deployments. It's weird how the error in tofu/terraform is reverse. But RDS is already running on *.40, so we should specify that.
=> Sync up tofu's mysql version with rds

backend/src/appointment/controller/apis/zoom_client.py, backend/src/appointment/exceptions/zoom_api.py, backend/src/appointment/l10n/de/main.ftl, backend/src/appointment/l10n/en/main.ftl, backend/src/appointment/routes/zoom.py
Fixes #996 for realies.
Basically we're experiencing a scope change error: https://thunderbird.sentry.io/issues/6561374703/?project=4505428124827648&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0
Where we seem to have initialized our app with the old scopes instead of the new scopes...which doesn't make sense because we set an env var to use new scopes. Since everything should be using new scopes, let's just use those and delete the old ones.
This also catches the scope change error and sends the user back an error message.
=> Only use one set of scopes, and catch any scope errors that may occur.

frontend/src/components/SettingsGeneral.vue, test/e2e/pages/settings-page.ts, test/e2e/tests/settings.spec.ts
Update the E2E settings tests to match the recent settings & share link page changes.
=> Update E2E test to match recent share link changes

test/e2e/pages/dashboard-page.ts, test/e2e/pages/splashscreen-page.ts
Update the E2E tests to wait longer for the dashboard to fully load because sometimes the availability / settings panel on the right side is taking a very long time to load (see issue #1015).
Also using this PR to increase the wait time allowed for the FxA sign-in page to load as I notice once and awhile the tests timeout waiting for FxA.
=> Increase E2E test wait time when loading dashboard

frontend/src/components/FTUE/SetupSchedule.vue, frontend/src/components/ScheduleCreation.vue, frontend/src/components/SettingsGeneral.vue, frontend/src/models.ts, frontend/src/stores/schedule-store.ts
This PR fixes a wrong type with the SelectOption value. I also reverted some of the stringified number select values where appropriate. I think it's best if we keep the `string | number` type for select values, since there are valid use cases for both imo.
Closes #1019
=> Fix type errors

frontend/src/App.vue, frontend/src/components/NavBar.vue, frontend/src/components/TitleBar.vue
This PR changes the visibility of the navbar:
- If a user is authenticated, the navbar is always shown with all available menu entries on all pages (even home and the availability page).
- If a user is **not** authenticated, the navbar is shown without menu entries but still with the logo on all pages, except for the homepage.
Home as authenticated user:
Availability as authenticated user:
Home as anonymous user:
Availability as anonymous user:
I also fixed a well hidden bug, where our routeIsHome or routeIsPublic checks failed, because we were using a constant in the corresponding computed properties instead of the route object itself.
The Thunderbird Appointment branding should now always be visible.
Closes #1007
=> Show navbar without menu on availability page

test/e2e/const/constants.ts, test/e2e/pages/dashboard-page.ts, test/e2e/tests/settings-general.spec.ts
Fixes #1029 on both [mobile](https://automate.browserstack.com/dashboard/v2/builds/e76dd3b7410ce632804a42ba22a7e26fc3529c1c/sessions/ff2f554daae6961ab6b7d3ddaad3d42c3bc77ef2) and [desktop](https://automate.browserstack.com/dashboard/v2/builds/0f7192bcd6e047aa55e3a99548cb1cb44d17ce28) browsers.
=> Update E2E time format test to also work on weekends

backend/src/appointment/migrations/versions/2025_06_09_2130-2b40448be2f5_fill_in_empty_short_link_hash_.py
Fixes #1057 
Short_link_hash was added in a later migration so some early users (like me actually!) have this set to None. This should have been caught earlier, but it's environment-specific.
=> Add a data migration to fill in short_link_hash if empty. (Fixes #1057)

frontend/src/components/ScheduleCreation.vue, frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/tbpro/elements/CheckboxInput.vue
In case Zoom is not enabled, there was no message to the subscriber explaining why they can't click on the checkbox to generate zoom meeting. This adds a message with a link to the related setting (`/settings/connectedAccounts`) and changes the cursor to `not-allowed` when checkboxes are disabled.
- Better feedback to the subscriber on the available actions around Zoom's settings to generate meeting link.
- Cursor update when checkbox is disabled for all usages of the `CheckboxInput` component
https://github.com/thunderbird/appointment/issues/973
=> Add explainer to "generate Zoom meeting checkbox" when Zoom is not connected

backend/src/appointment/database/models.py
There was a typo mistake on the `uuid` column type from the `appointments` table. It was supposed to use `Uuid` instead of `UUID`. Original problem was introduced in this PR: https://github.com/thunderbird/appointment/pull/1075
Database initialization and migrations actually work.
https://github.com/thunderbird/appointment/issues/1080
=> Change appointment uuid type from UUID to Uuid

frontend/src/components/NavBar.vue, frontend/src/elements/UserAvatar.vue
As part of the UI overhaul, adding a copy link icon button and user email to the navbar per wireframes.
Be able to copy the appointment link from anywhere is handy! Also, seeing the name of the account is more clear than just the initials on the user avatar.
https://github.com/thunderbird/appointment/issues/1088
=> Add copy link icon and email to navbar

tofu/environments/prod/environment.hcl, tofu/environments/stage/environment.hcl
AWS released a new major version of their Terraform provider with a number of significant changes in it. Since we are replacing this Terraform code with Pulumi code, it's not worth it to do a full provider upgrade here. Instead, I'm replacing the [version constraint](https://developer.hashicorp.com/terraform/language/providers/requirements#version-constraints) with this `~=` constraint, which allows the rightmost semver digit to increment. This will prevent us from using the new major version while still getting the latest from the old major version.
=> Lock Terraform AWS provider version

tofu/environments/prod/environment.hcl, tofu/environments/stage/environment.hcl
I think this should push along the Tofu deployments.
=> Lock random package so it doesn't depend on newer aws package

backend/src/appointment/controller/mailer.py, backend/src/appointment/defines.py, backend/src/appointment/middleware/l10n.py
Although the backend service works well, when mail templates are referenced, they fail to resolve correctly as the copy from the Dockerfile says `COPY src .` and the expected path for Mailpit Jinja templates is `src/appointment/templates/email`.
We could either do the change back from the Dockerfile _or_ change the [`get_jinja()` function from the mailer](https://github.com/thunderbird/appointment/blob/main/backend/src/appointment/controller/mailer.py#L23) and [`get_fluent()` function from the I10n](https://github.com/thunderbird/appointment/blob/main/backend/src/appointment/middleware/l10n.py#L15) and potentially other places that I might be missing.
~~For brevity, changing the Dockerfile back makes it work it again locally but unsure if this breaks other parts of the infra.~~
As …
=> Fix backend's base URL paths for Mailpit & Fluent

.github/workflows/deploy-staging.yml
The problem solved here is that the second setting of AWS credentials fails to swap the new session out for the old one. So here we separate the Pulumi env image build into its own job context.
=> Move Pulumi build to separate job

.github/workflows/deploy-staging.yml
This prevents a case where we try to do a backend image deployment before we have completed a backend image build.
=> Don't run backend deploy on failure/noncompletion

pulumi/__main__.py
This only pops up if you try to build a bastion. I tried that today and got a missing import error that this change fixes.
=> Add tb_pulumi.ec2 import

README.md, backend/.env.example, backend/alembic.ini.example, backend/pyproject.toml, backend/src/appointment/utils.py, docker-compose.yml, docs/README.md
- Changed adapter from `mysqldb` to `[psycopg](https://pypi.org/project/psycopg/)` (psycopg3)
- Updated `docker-compose.yml`
- Updated project architecture diagram with the recent DB changes
- Added `external_connection_id` foreign key in `Calendars`
- Changed `uuid` comment to be `Uuid` instead of `Binary`
Note: I did not update the `tofu` / `infra` yet so that it can be done alongside the Neon (?) integration
> [!WARNING]  
> It is necessary to delete all the container / volumes for this to work so you will lose all your data when testing this
To remove all your volumes, navigate to your `appointment` root folder and:
```bash
$ docker-compose down -v
```
- Hopefully a more seamless transition to Neon's Postgresql and having a local dev environment that will use the same DB backend as …
=> Switch from MySQL to PostgreSQL

pulumi/Pulumi.stage.yaml, pulumi/config.stage.yaml
If Phase One was "Fix DB Connection Strings and the Variables that Construct It", then this is Phase Two: Make the Task Definition Use Those Variables. This keeps the service pointed at the existing MySQL database and gives us a safe rollback point in case the Postgres migration doesn't go well.
=> Set up new task def for stage/mysql

frontend/.env.prod.example, frontend/.env.pulumiprod.example, frontend/.env.pulumistage.example, frontend/.env.stage.example
Updates to `VITE_SUPPORT_URL` across the various `*.example` files
- Self-hosted Zendesk form allows us to keep a more cohesive experience across products instead of yeeting the user to Zendesk's domain.
https://github.com/thunderbird/appointment/issues/892
=> Update VITE_SUPPORT_URL to new self-hosted Zendesk form

frontend/src/locales/de.json, frontend/src/locales/en.json, frontend/src/models.ts, frontend/src/stores/availability-store.ts, frontend/src/stores/settings-store.ts, frontend/src/views/AvailabilityView/components/AvailabilitySettings/index.vue, frontend/src/views/AvailabilityView/components/BookingPageLink/index.vue, frontend/src/views/AvailabilityView/index.vue, frontend/src/views/SettingsView/components/ConnectedApplications.vue, frontend/src/views/SettingsView/index.vue
This PR fixes a few problems but also opens up new questions on how to handle some scenarios:
1. In the Settings page, we were coupling the calendar updates with the first / default schedule since the `default` calendar can be changed in this page to any other connected calendar. This is a problem because if a user removes all of the accounts / has no calendars, they would also have no schedule anymore. [Adding a check here solves it](https://github.com/thunderbird/appointment/pull/1200/files#diff-f09242ff792588c8b0041051932ba73857622a2d2057991ca39ae2db73c09e12R139-R143). [I've also added a placeholder message](https://github.com/thunderbird/appointment/pull/1200/files#diff-fdd0b20f6fd56a7487b6aa97d100fe585694f85bd7db1c531ee100dc8a8d942aR247) (copy not approved yet) for the empty state. …
=> [Hotfix?] First schedule may not exist when accounts are disconnected / reconnected

test/e2e/pages/settings-page.ts, test/e2e/tests/settings-account.spec.ts, test/e2e/tests/settings-language.spec.ts, test/e2e/tests/settings-start-of-week.spec.ts, test/e2e/tests/settings-theme.spec.ts, test/e2e/tests/settings-timezone.spec.ts, test/e2e/utils/utils.ts
More additions and improvements to settings tests:
- Update account settings test to check for display name and download data button
- Add a test to change the display name, verify changed on book appointment (share link) page
- Add some `expect.soft`'s to some of the settings tests to ensure the test continues to run (and set the settings back to their original state) even if the test assert fails (test is still marked as a failure in that case)
- In the `able to change start of week` test temporarily remove the start of week check on the dashboard, as this is currently failing because the dashboard calendar UI is being overhauled; will add this back after that is complete
=> E2E settings test updates

pulumi/__main__.py, pulumi/requirements.txt
When the stack access policies have been built, create a CI user for the environment and place it in that environment's admin group.
We get a cleaner separation of powers between the environments. In the current model, we have one CI account with limited access to all environments. This grants admin access to the CI user, but only to a single environment.
This is dependent upon [this PR](https://github.com/thunderbird/pulumi/pull/211).
=> Create a CI user, add to environmental admin group

pulumi/__main__.py, pulumi/config.stage.yaml
We have switched over to the new `StackAccessPolicies` model of permissions, and we no longer need this old CI config.
Unnecessary path to environmental access revoked.
=> Delete old automation user

pulumi/__main__.py, pulumi/config.prod.yaml, pulumi/config.stage.yaml
We just switched over to using StackAccessPolicies for access, and it seems the issue with that is we lack certain policies for resources that exist outside the scope of a stack (like an ECR repository, for example). These are the things that the AwsAutomationUser was built for, and I just got rid of those. That was a mistake.
When reinstating those CI permissions, I found a number of improvements to make in this code, and therfore this PR has come to exist.
Get appropriate CI permissions scoped to the environment.
=> Reinstate AwsAutomationUser

pulumi/Pulumi.prod.yaml, pulumi/config.prod.yaml
There is a ton of detail in Issue #1110. This change was previously made in stage with PR #1270. This separates the JSONified values into separate config options in PROD, moving some into new secrets and some into plaintext env-vars.
Better visibility into the running app config. Better granularity in our ability to make changes.
#1110
The change in the task definition is shown by [this `pulumi preview` command](https://app.pulumi.com/mzla-services/appointment/prod/previews/01f5351d-2ac1-42b3-9eae-0d09904fc42a).
=> Separate JSONified values into individual values in prod

backend/.env.test, backend/src/appointment/utils.py, docker-compose.yml, pulumi/config.prod.yaml
This removes the last of the secrets from the prod environment. It also adjusts the code that generates database URLs because we use sqlite in our tests. I tried finding the right individual settings to support in-memory sqlite, but nothing worked easily. So we will continue to support `DATABASE_URL` for the sqlite use case.
[Here is the pulumi diff](https://app.pulumi.com/mzla-services/appointment/prod/previews/3258a7b2-798c-46c8-a471-b50156c72698) for the task definition.
Clean, tidy code with less configuration obscurity.
#1110
=> Remove old JSONified secrets from prod
